# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'ITDaysDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ITDaysDemo
  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa'
  pod 'RxGesture'
  pod 'ObservableArray-RxSwift'
  pod 'Alamofire'
  target 'ITDaysDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ITDaysDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
